name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  zard:
    path: ../
  intl: ^0.20.2
  # path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
